import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../../_src/css/app.css';
import clsx from 'clsx';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={clsx(
          'bg-gray-900 text-white light-mode:bg-gray-100 light-mode:text-gray-900',
          inter.className
        )}
      >
        {children}
      </body>
    </html>
  );
}
